---
title: "Statistical Rethinking"
output: html_notebook
---

### Set up
<i> Install libraries </i>
```{r}
# install.packages(c("coda", "mvtnorm", "devtools"))
# devtools::install_github("rmcelreath/rethinking")
```

<i> Load libraries </i>
```{r}
library(rethinking)
```


### Chapter 4
<i> Read data </i>
```{r}
data("Howell1")
d  <- Howell1
d2 <- d[d$age >= 18, ]
```

Plot prior distribution of h(height)
```{r}
sample_mu <- rnorm(1e4, 178, 20)
sample_sd <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sd)
dens(prior_h)
```

R code 4.14 (edited)
```{r}
Calc_LogLik <- function(i) {
   sum(dnorm(d2$height, mean = post$mu[i], sd = post$sd[i], log = TRUE))
}
mu_list <- seq(from = 140, to = 160, length.out = 200)
sd_list <- seq(from = 4, to = 9, length.out = 200)
post    <- expand.grid(mu = mu_list, sd = sd_list)
post$LL <- sapply(1:nrow(post), Calc_LogLik)

post$prob    <- post$LL + 
   dnorm(post$mu, 178, 20, TRUE) + 
   dunif(post$sd, 0, 50, TRUE)
post$prob_02 <- exp(post$prob - max(post$prob))
```


```{r}
contour_xyz(post$mu, post$sd, post$prob)
```

```{r}
image_xyz(post$mu, post$sd, post$prob)
```


```{r}
sample_rows <- sample(1:nrow(post), size = 1e4, replace = TRUE,
                      prob = post$prob_02)
sample_mu <- post$mu[sample_rows]
sample_sd <- post$sd[sample_rows]
```


```{r}
plot(sample_mu, sample_sd, cex = 0.5, pch = 16, col = col.alpha(rangi2, 0.1))
```

```{r}
dens(sample_mu)
```

```{r}
dens(sample_sd)
```


```{r}
HPDI(sample_mu)
```

```{r}
HPDI(sample_sd)
```


```{r}
flist <- alist(
   height ~ dnorm(mu, sd),
   mu ~ dnorm(178, 20),
   sd ~ dunif(0, 50)
)
```

```{r}
m4.1 <- map(flist, data = d2)
precis(m4.1)
```

```{r}
m4.2 <- map(alist(
   height ~ dnorm(mu, sd),
   mu ~ dnorm(178, 0.1),
   sd ~ dunif(0, 50)), data = d2)
precis(m4.2)
```



```{r}
plot(d2$height, d2$weight)
```



```{r}
m4.3 <- map(
   alist(
      height ~ dnorm(mu, sd),
      mu <- a + b * weight,
      a ~ dnorm(156, 100),
      b ~ dnorm(0, 10),
      sd ~ dunif(0, 50)
   ),
   data = d2
)
precis(m4.3, corr = TRUE)
```


```{r}
d2$weight.c <- d2$weight - mean(d2$weight)
```

```{r}
m4.4 <- map(
   alist(
      height ~ dnorm(mu, sd),
      mu <- a + b * weight.c,
      a ~ dnorm(156, 100),
      b ~ dnorm(0, 10),
      sd ~ dunif(0, 50)
   ),
   data = d2
)
precis(m4.4, corr = TRUE)
```



```{r}
N  <- 10
dN <- d2[1:N, ]
mN <- map(
   alist(
      height ~ dnorm(mu, sd),
      mu <- a + b * weight,
      a ~ dnorm(178, 100),
      b ~ dnorm(0, 10),
      sd ~ dunif(0, 50)
   ),
   data = dN
)
```

```{r}
post <- extract.samples(mN, n = 20)
plot(dN$weight, dN$height, xlim = range(d2$weight), ylim = range(d2$height),
     col = rangi2, xlab = "weight", ylab = "height")
mtext(concat("N = ", N))
for (i in 1:20) {
   abline(a = post$a[i], b = post$b[i], col = col.alpha("black", 0.3))
}
```

```{r}
post <- extract.samples(m4.3, n = 1e4)
mu_at_50 <- post$a + post$b * 50
dens(mu_at_50, col = rangi2, lwd = 2, xlab = "mu | weight = 50")
```

```{r}
HPDI(mu_at_50, prob = 0.89)
```



```{r}
weight.seq <- seq(from = 25, to = 70, by = 1)
mu <- link(m4.3, data = data.frame("weight" = weight.seq))
str(mu)
```




```{r}
plot(height ~ weight, d2, type = "n")
for (i in 1:1000) {
   points(weight.seq, mu[i, ], pch = 16, col = col.alpha(rangi2, 0.1))
}
```

```{r}
mu.mean <- apply(mu, 2, mean)
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.89)
```

```{r}
plot(height ~ weight, d2, col = col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.HPDI, weight.seq)
```


```{r}
sim.height <- sim(m4.3, data = list(weight = weight.seq))
str(sim.height)
```



```{r}
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
plot(height ~ weight, d2, col = col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.HPDI, weight.seq)
shade(height.PI, weight.seq)
```



```{r}
plot(d$height ~ d$weight)
```

```{r}
d$weight.s <- (d$weight - mean(d$weight)) / sd(d$weight)
plot(d$height ~ d$weight.s)
```


```{r}
d$weight.s2 <- d$weight.s ^ 2
m4.5 <- map(
   alist(
      height ~ dnorm(mu, sd),
      mu <- a + b * weight.s + c * weight.s2,
      a ~ dnorm(156, 100),
      b ~ dnorm(0, 10),
      c ~ dnorm(0, 10),
      sd ~ dunif(0, 50)
   ),
   data = d
)
precis(m4.5, corr = TRUE)
```


```{r}
weight.seq <- seq(from = -2.2, to = 2, length.out = 30)
pred_dat <- list(weight.s = weight.seq, weight.s2 = weight.seq ^ 2)
mu <- link(m4.5, data = pred_dat)
mu.mean <- apply(mu, 2, mean)
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.89)
mu.PI   <- apply(mu, 2, PI, prob = 0.89)
sim.height <- sim(m4.5, data = pred_dat)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)

plot(height ~ weight.s, d, col = col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```

```{r}
d$weight.s3 <- d$weight.s ^ 3
m4.6 <- map(
   alist(
      height ~ dnorm(mu, sd),
      mu <- a + b * weight.s + c * weight.s2 + d * weight.s3,
      a ~ dnorm(156, 100),
      b ~ dnorm(0, 10),
      c ~ dnorm(0, 10),
      d ~ dnorm(0, 10),
      sd ~ dunif(0, 50)
   ),
   data = d
)
precis(m4.6, corr = TRUE)
```


```{r}
weight.seq <- seq(from = -2.2, to = 2, length.out = 30)
pred_dat <- list(weight.s = weight.seq, weight.s2 = weight.seq ^ 2,
                 weight.s3 = weight.seq ^ 3)
mu <- link(m4.6, data = pred_dat)
mu.mean <- apply(mu, 2, mean)
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.89)
mu.PI   <- apply(mu, 2, PI, prob = 0.89)
sim.height <- sim(m4.6, data = pred_dat)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)

plot(height ~ weight.s, d, col = col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```


### Chapter 5
```{r}
data("WaffleDivorce")
d <- WaffleDivorce
```

```{r}
d$MedianAgeMarriage.s <- (d$MedianAgeMarriage - mean(d$MedianAgeMarriage)) /
   sd(d$MedianAgeMarriage)
m5.1 <- map(
   alist(
      Divorce ~ dnorm(mu, sd),
      mu <- a + bA * MedianAgeMarriage.s,
      a  ~ dnorm(10, 10),
      bA ~ dnorm(0, 1),
      sd ~ dunif(0, 10)
   ), data = d
)
```

```{r}
MAM.seq <- seq(from = -3, to = 3.5, length.out = 30)
mu <- link(m5.1, data = data.frame(MedianAgeMarriage.s = MAM.seq))
mu.PI <- apply(mu, 2, PI)

plot(Divorce ~ MedianAgeMarriage.s, data = d, col = rangi2)
abline(m5.1)
shade(mu.PI, MAM.seq)
```


```{r}
d$Marriage.s <- (d$Marriage - mean(d$Marriage)) /
   sd(d$Marriage)
m5.2 <- map(
   alist(
      Divorce ~ dnorm(mu, sd),
      mu <- a + bR * Marriage.s,
      a  ~ dnorm(10, 10),
      bR ~ dnorm(0, 1),
      sd ~ dunif(0, 10)
   ), data = d
)
```

```{r}
MAM.seq <- seq(from = -3, to = 3.5, length.out = 30)
mu <- link(m5.2, data = data.frame(Marriage.s = MAM.seq))
mu.PI <- apply(mu, 2, PI)

plot(Divorce ~ Marriage.s, data = d, col = rangi2)
abline(m5.2)
shade(mu.PI, MAM.seq)
```


```{r}
m5.3 <- map(
   alist(
      Divorce ~ dnorm(mu, sd),
      mu <- a + bA * MedianAgeMarriage.s + bR * Marriage.s,
      a  ~ dnorm(10, 10),
      bA ~ dnorm(0, 1),
      bR ~ dnorm(0, 1),
      sd ~ dunif(0, 10)
   ), data = d
)
precis(m5.3)
```

```{r}
plot(precis(m5.3))
```


```{r}
m5.4 <- map(
   alist(
      Marriage.s ~ dnorm(mu, sd),
      mu <- a + bA * MedianAgeMarriage.s,
      a  ~ dnorm(0, 10),
      bA ~ dnorm(0, 1),
      sd ~ dunif(0, 10)
   ), data = d
)
precis(m5.4, corr = TRUE)
```

<i><b> Note the definition of "lines" </b></i>

```{r}
mu <- coef(m5.4)['a'] + coef(m5.4)['bA'] * d$MedianAgeMarriage.s
m.resid <- d$Marriage.s - mu

plot(Marriage.s ~ MedianAgeMarriage.s, d, col = rangi2)
abline(m5.4)
for(i in 1:length(m.resid)) {
   x <- d$MedianAgeMarriage.s[i]
   y <- d$Marriage.s[i]
   lines(c(x, x), c(mu[i], y), lwd = 0.5, col = col.alpha("black", 0.7))
}
```

```{r}
A.avg <- mean(d$MedianAgeMarriage.s)
R.seq <- seq(from = -3, to = 3, length.out = 30)
pred.data <- data.frame(
   Marriage.s <- R.seq,
   MedianAgeMarriage.s <- A.avg
)

mu <- link(m5.3, data = pred.data)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI)

R.sim <- sim(m5.3, data = pred.data, n=1e4)
R.PI <- apply(R.sim, 2, PI)

plot(Divorce ~ Marriage.s, data = d, type = "n")
lines(R.seq, mu.mean)
shade(mu.PI, R.seq)
shade(R.PI, R.seq)
```


```{r}
R.avg <- mean(d$Marriage.s)
A.seq <- seq(from = -3, to = 3, length.out = 30)
pred.data <- data.frame(
   Marriage.s <- R.avg,
   MedianAgeMarriage.s <- A.seq
)

mu <- link(m5.3, data = pred.data)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI)

A.sim <- sim(m5.3, data = pred.data, n=1e4)
A.PI <- apply(A.sim, 2, PI)

plot(Divorce ~ MedianAgeMarriage.s, data = d, type = "n")
mtext("Marriage.s = 0")
lines(A.seq, mu.mean)
shade(mu.PI, R.seq)
shade(A.PI, R.seq)
```


```{r}
mu <- link(m5.3)

mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI)

divorce.sim <- sim(m5.3, n = 1e4)
divorce.PI <- apply(divorce.sim, 2, PI)

plot(mu.mean ~ d$Divorce, col = rangi2, ylim = range(mu.PI),
     xlab = "Observed divorce", ylab = "Predicted divorce")
abline(a = 0, b = 1, lty = 2)
for (i in 1:nrow(d)) {
   lines(rep(d$Divorce[i], 2), c(mu.PI[1, i], mu.PI[2, i]),
         col = rangi2)
}
identify(x = d$Divorce, y = mu.mean, labels = d$Loc, cex = 0.8)
```



```{r}
divorce.resid <- d$Divorce - mu.mean

o <- order(divorce.resid)

dotchart(divorce.resid[o], labels = d$Loc[o], xlim = c(-6, 5), cex = 0.6)
abline(v = 0, col = col.alpha("black", 0.2))
for(i in 1:nrow(d)) {
   j <- o[i]
   lines(d$Divorce[j] - c(mu.PI[1, j], mu.PI[2, j]), rep(i, 2))
   points(d$Divorce[j] - c(divorce.PI[1, j], divorce.PI[2, j]), rep(i, 2),
          pch = 3, cex = 0.6, col = "gray")
}
```


```{r}
N <- 100
x_real <- rnorm(N)
x_spur <- rnorm(N, x_real)
y <- rnorm(N, x_real)
d <- data.frame(y, x_real, x_spur)
```

```{r}
cor(d)
pairs(d)
```

```{r}
model_xx <- map(
   alist(
      y ~ dnorm(mu, sd),
      mu <- a + b1 * x_real + b2 * x_spur,
      a  ~ dnorm(0, 10),
      b1 ~ dnorm(0, 1),
      b2 ~ dnorm(0, 1),
      sd ~ dunif(0, 10)
   ), data = d
)
precis(model_xx, corr = TRUE)
```

```{r}
post <- extract.samples(model_xx, 1e4)
cor(post)
pairs(post)
```



